env: "prod" # local, dev, prod

sqlite:
  storage_path: "./storage/sqlite_storage.db"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "" # чувствительные данные
  dbname: "url-shortener"
  sslmode: "disable"

http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s

db_type: "postgres" # выбрать: sqlite или postgres