env: "local" # local, dev, prod

sqlite:
  storage_path: "./storage/sqlite.db"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "ivanMENSHIKH150%" # чувствительные данные
  dbname: "urlShortener"
  sslmode: "disable"

http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
  user: "admin"
  password: "admin"

db_type: "postgres" # выбрать: sqlite или postgres